config/routes.rb
Rails.application.routes.draw do
  devise_for :users do
    resources :meetings, only: %i[create]
  end

  root to: "pages#home"

  resources :locallers, only: %i[index show new create edit update] do
    resources :meetings, only: %i[create]
  end

  resources :meetings, only: %i[destroy]

  resources :chats, only: %i[index show create] do
    resources :messages, only: :create
  end

  get '/dashboard', to: 'dashboards#profile'
  get '/dashboard/:id', to: 'dashboards#show', as: "profile"
end

app/models/activity.rb
class Activity < ApplicationRecord
  has_many :localler_activities

  validates :title, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chat.rb
class Chat < ApplicationRecord
  has_many :messages
  has_many :meetings
  belongs_to :localler
  belongs_to :user
end

app/models/localler.rb
class Localler < ApplicationRecord
  belongs_to :user
  has_many :localler_activities
  has_many :activities, through: :localler_activities
  has_many :chats
  has_many :meetings
  
  validates :description, :location, presence: true
  validates :description, length: { minimum: 130, maximum: 500 }
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
end

app/models/localler_activity.rb
class LocallerActivity < ApplicationRecord
  belongs_to :activity
  belongs_to :localler
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :user
  belongs_to :localler
  belongs_to :chat

  validates :time, :location, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chat
  belongs_to :user

  def create
    # need content in strong params, chat_id and user_id
    @message = Message.new(message_params)
    @message.user = current_user
    @message.chat = Chat.find(params[:chat_id])
  end

  def sender?(a_user)
    user.id == a_user.id
  end
  
  private

  def message_params
    params.require(:message).permit(:content)
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :meetings
  has_one :localler
  has_many :messages
  has_many :chats
  has_one_attached :profile_picture

  validates :username, uniqueness: true
  validates :bio, length: { minimum: 50, maximum: 500 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[username bio profile_picture])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: %i[username bio profile_picture])
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def index
    @chats = current_user.chats.includes(:user)
    @chats = current_user.chats.includes(:user) + current_user.localler.chats.includes(:localler) if current_user.localler
  end

  def show
    @chat = Chat.find(params[:id])
    @localler = @chat.localler
    @user = @chat.user
    @meeting = Meeting.new
    @localler_meetings = @chat.meetings.where localler: @localler
    @user_meetings = @chat.meetings.where user: @user

    if @chat.user != current_user && @chat.localler.user != current_user
      redirect_to locallers_path, notice: "You don't have access to this chat"
    end
    @message = Message.new
  end

  def create
    @chat = Chat.create(user: current_user, localler_id: params[:localler])
    redirect_to chat_path(@chat)
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    # this will be a user's public profile page
  end

  def profile
    @user = current_user
  end
end

app/controllers/locallers_controller.rb
class LocallersController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    @locallers = Localler.includes([:user, :activities]).near(params[:query], 50)
    @locallers = Localler.all if @locallers.empty?
    @activities = Activity.all
    if params[:filter].present?
      @locallers = @locallers.joins(:activities).where(activities: { title: params[:filter] })
    end
    # The `geocoded` scope filters only locallers with coordinates (latitude & longitude)
    @markers = @locallers.geocoded.map do |localler| {
      lat: localler.latitude,
      lng: localler.longitude,
      info_window_html: render_to_string(partial: "info_window", locals: { localler: localler }),
      marker_html: render_to_string(partial: "marker", locals: { localler: localler })
    }
    end
  end

  def new
    @localler = Localler.new
  end

  def create
    # Check if the user has already a localler_id
    if current_user.localler
      redirect_to root_path, alert: "You already are a localler ❤️"
      return
    end
    # Create a new localler
    @localler = Localler.new(localler_params)
    @localler.user = current_user
    if @localler.save
      redirect_to localler_path(@localler)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @chat = Chat.new
    @localler = Localler.find(params[:id])

    # The `geocoded` scope filters only locallers with coordinates
    @markers = [{
      lat: @localler.latitude,
      lng: @localler.longitude,
      info_window_html: "",
      marker_html: render_to_string(partial: "marker", locals: { localler: @localler })
    }]
  end

  def update
    @localler = Localler.find(params[:id])
    @localler.update(localler_params)
    redirect_to request.referer
  end

  private

  def localler_params
    params.require(:localler).permit(:description, :location, :availability, activity_ids: [])
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  def create
    @meeting = Meeting.new(meeting_params)
    @localler = Localler.find(params[:localler_id])
    @meeting.localler = @localler
    @chat = Chat.find(params[:meeting][:chat_id].to_i)
    @meeting.user = @chat.user
    if @meeting.save
      redirect_to chat_path(@chat)
    else
      render 'chats/show', notice: 'Something went wrong with your booking. Please try again.', status: :unprocessable_entity
    end
  end

  def destroy
    @meeting = Meeting.find(params[:id])
    @meeting.destroy
    redirect_to dashboard_path
  end

  private

  def meeting_params
    params.require(:meeting).permit(:time, :location, :chat_id)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @chat = Chat.find(params[:chat_id])
    @message = Message.new(message_params)
    @message.chat_id = @chat.id
    @message.user_id = current_user.id

    if @message.save
      ChatChannel.broadcast_to(
        @chat,
        message: render_to_string(partial: "message", locals: { message: @message }),
        sender_id: @message.user.id
      )
      head :ok
    else
      render 'chats/show', status: :unprocessable_entity
    end
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[home]

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chats/index.html.erb
<div class="bg-index">
  <div class="pages">
    <div class="messages-index">
      <div class="container">

        <h2><i class="fa-solid fa-envelope"></i> My Chats</h2>
        <% if @chats.any? %>
          <% @chats.each do |chat| %>
            <div class="card card-chats">
              <div class="card-body">
                <div class="card-title">
                  <% if current_user != chat.localler.user %>
                    <h4 class="fw-bold ps-1 pb-1"><%= chat.localler.user.username %></h4>
                  <% else %>
                    <h4 class="fw-bold ps-1 pb-1"><%= chat.user.username %></h4>
                  <% end %>
                </div>

            <% if chat.meetings.any? %>
              <div class="meeting-notice">
                <% if current_user == chat.user %>
                  <p>You're meeting with <%= chat.localler.user.username %> on <%= chat.meetings.last.time.strftime("%A, %d %b %Y %l:%M %p") %> in <%= chat.meetings.last.location %></p>
                <% else %>
                  <p>You're meeting with <%= chat.user.username %> on <%= chat.meetings.last.time.strftime("%A, %d %b %Y %l:%M %p") %> in <%= chat.meetings.last.location %></p>
                <% end %>
              </div>
            <% end %>

                <div class="text-center">
                  <%= link_to "Open chat", chat_path(chat), class:"green-button-chat w-100 mb-2" %>
                  <% if current_user == chat.user %>
                    <%= link_to "See Profile", localler_path(chat.localler), class:"black-button-chat w-100" %>
                  <% else %>
                    <%= link_to "See Profile", profile_path(chat.user), class:"black-button-chat w-100" %>
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
        <% else %>
          <p class="pt-4 text-center">You currently have no open chats...</p>
          <div style="width:100%;height:0;padding-bottom:56%;position:relative;"><iframe src="https://giphy.com/embed/jc2PkKKr3clTBekMzn" width="100%" height="100%" style="position:absolute" frameBorder="0" class="giphy-embed" allowFullScreen></iframe></div><p><a href="https://giphy.com/gifs/hero0fwar-sad-pablo-escobar-jc2PkKKr3clTBekMzn"></a></p>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/chats/show.html.erb
<div class="background-chat">
  <div class="pages">
    <div class="container chatroom"
      data-controller="chat-subscription"
      data-chat-subscription-id-value="<%= @chat.id %>"
      data-chat-subscription-current-user-id-value="<%= current_user.id %>">

      <h2>
        <% if @localler != current_user.localler %>
          <%= @localler.user.username %>
        <% else %>
          <%= @user.username %>
        <% end %>
      </h2>


      <% if @localler == current_user.localler && @localler_meetings.any?  %>
        <div class="meeting-notice">
          <p>You're meeting <%= @user.username %> on <%= @localler_meetings.last.time.strftime("%A, %d %b %Y %l:%M %p") %> in <%= @localler_meetings.last.location %></p>
        </div>
      <% end %>

      <% if @localler != current_user.localler && @user_meetings.any? %>
        <div class="meeting-notice">
          <p>You're meeting <%= @localler.user.username %> on <%= @user_meetings.last.time.strftime("%A, %d %b %Y %l:%M %p") %> in <%= @user_meetings.last.location %></p>
        </div>
      <% end %>

      <div class="messages" data-chat-subscription-target="messages">
        <% @chat.messages.each do |message| %>
          <div class="message-row d-flex <%= message.sender?(current_user) ? 'justify-content-end' : 'justify-content-start' %>">
            <div class="<%= message.sender?(current_user) ? 'sender-style' : 'receiver-style' %>">
              <%= render "messages/message", message: message %>
            </div>
          </div>
        <% end %>
      </div>

      <div>
        <%= simple_form_for [@chat, @message],
        html: { data: { controller: "message-form", action: "turbo:submit-end->chat-subscription#resetForm turbo:submit-end->message-form#toggleButton" }, class: "d-flex justify-content-center" } do |f| %>
        <%= f.input :content,
          label: false,
          placeholder: "Message...",
          wrapper_html: {class: "flex-grow-1 rounded-4 align-content-center", id: "message-send"},
          input_html: {class: "message-input-content", data: { action: "input->message-form#toggleButton", message_form_target: "input" }}
        %>
          <%= f.button :button, id: "send-button", data: { message_form_target: "button" }, disabled: true do %>
            <i class="fa-regular fa-paper-plane"></i>
          <% end %>
        <% end %>
      </div>
    <%#  add modal for booking %>

      <% if @localler == current_user.localler %>


        <button type="button" class="green-button-chat" data-bs-toggle="modal" data-bs-target="#exampleModal">
          Meet up with <%= @user.username %>!
        </button>

        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Confirm your meet up with <%= @user.username %>:</h1>

                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                <%= simple_form_for [@localler, @meeting] do |f| %>
                  <%= f.input :time,
                  as: :string,
                  input_html: { data: { controller: "datepicker" } } %>
                  <%= f.hidden_field :chat_id, value: @chat.id %>
                  <%= f.input :location, label: "Location" %>
                  <%= f.button :submit, "Confirm", class: "black-button-chat" %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/dashboards/profile.html.erb
<div class="bg-index">
  <div class="pages">

    <div class="container pb-3">

      <h2><i class="fa-solid fa-user"></i> My Profile</h2>

      <div class="local-block d-flex align-items-center">
        <%= cl_image_tag current_user.profile_picture.key, class: "rounded-circle img-fluid border-2", style: "width: 100px; height: 100px; object-fit: cover" %>
        <div class="ms-4">
          <h3><%= @user.username %></h3>
        </div>
      </div>

      <div class="local-bio">
        <h3 class="pt-2">Bio</h3>
        <p><%= @user.bio %></p>
      </div>

      <%= link_to "Edit my profile", edit_user_registration_path, class: "green-button-become mt-2" %>
    </div>

  </div>
</div>

app/views/dashboards/show.html.erb
<div class="bg-index">
  <div class="pages">

    <div class="container pb-3">

      <h2><i class="fa-solid fa-user"></i> Profile</h2>

      <div class="local-block d-flex align-items-center">
        <%= cl_image_tag @user.profile_picture.key, class: "rounded-circle img-fluid border-2", style: "width: 100px; height: 100px; object-fit: cover" %>
        <div class="ms-4">
          <h3><%= @user.username %></h3>
        </div>
      </div>

      <div class="local-bio">
        <h3 class="pt-2">Bio</h3>
        <p><%= @user.bio %></p>
      </div>

    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Locally</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <%= favicon_link_tag 'icons/favicon.ico' %>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <link rel="manifest" href="<%= asset_path 'manifest.json' %>">
      <%= render 'shared/ios_pwa_links' %>

  </head>

  <body>
    <% if params[:action] == "home" || params[:controller] == "chats" %>
      <%= render "shared/navbar2" %>
    <% else %>
      <%= render "shared/navbar" %>
    <% end %>
    <%= render "shared/flashes" %>
    <%= yield %>
  </body>
</html>

app/views/locallers/_form.html.erb
<div class="bg-index">
  <div class="pages">
    <%= simple_form_for [@localler] do |f| %>
      <div class="form-inputs localler-creating">
        <%= f.input :description %>
        <%= f.input :location %>
        <%= f.association :activities, as: :check_boxes %>
      </div>
      <div class="form-actions">
        <%= f.button :submit, class: "green-button-login" %>
      </div>
    <% end %>
  </div>
</div>

app/views/locallers/_info_window.html.erb
<div class="info-window">
  <%= link_to localler_path(localler), class: "navbar-brand" do %>
    <h3 class="h3-map"><%= localler.user.username %></h3>
  <% end %>
</div>

app/views/locallers/_marker.html.erb
<% if localler.availability == true %>
  <%= image_tag "pin_online_character.png", height: 28, width: 13, alt: "Logo" %>
<% else %>
  <%= image_tag "pin_offline_character.png", height: 28, width: 13, alt: "Logo" %>
<% end %>

app/views/locallers/index.html.erb
<div class="bg-index">
  <div class="pages">
    <div class="container pb-3">
      <h2><i class="fa-solid fa-arrows-rotate"></i> Locallers around</h2>

      <div class="carousel">
        <div class="card-carousel-container">
          <% @activities.each do |activity| %>
            <div class="card-carousel"><%= link_to activity.title, locallers_path(filter: activity.title, query: params[:query]),
            class: "#{params[:filter] == activity.title ? "my-button-active" : "my-button"}" %>
            </div>
          <% end %>
        </div>
      </div>

      <div style="width: 100%; height: 300px;"
        data-controller="map"
        data-map-markers-value="<%= @markers.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>

      <div>
        <% @locallers.each do |localler| %>
          <%= link_to localler_path(localler) do %>
            <div class="card-locallers d-flex">
              <%= cl_image_tag localler.user.profile_picture.key, class: "avatar-card", alt: "profile picture" %>
              <div class="card-info">
                <div class="d-flex justify-content-between align-items-top">
                  <div>
                    <h3 id="name-card-index-page"><%= localler.user.username %></h3>
                  </div>
                    <% if (localler.availability) == true %>
                      <i class="fa-solid fa-circle" id="available-green"></i>
                    <% else %>
                      <i class="fa-solid fa-circle" id="available-orange"></i>
                    <% end %>
                </div>
                <div>
                  <p> <%= localler.description %> </p>
                </div>
                <div>
                  <% localler.activities.each_with_index do |activity, i| %>
                    <% if (i + 1) == localler.activities.length %>
                      <p class="my-button"><%= activity.title %></p>
                    <% else %>
                      <p class="my-button"><%= activity.title %> | </p>
                    <% end %>
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/locallers/new.html.erb
<div class="bg-index">
  <div class="pages">
    <div class="container pb-3">
      <h2>Become a localler!</h2>

      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/locallers/show.html.erb
<div class="bg-index">
  <div class="pages">

    <div class="container pb-3">
      <div class="local-block d-flex align-items-center">
        <%= cl_image_tag @localler.user.profile_picture.key, alt: "avatar", class: "rounded-circle img-fluid border-2", style: "width: 100px; height: 100px; object-fit: cover" %>
        <div class="ms-4">
          <h3><%= @localler.user.username %></h3>
          <p class="city"><%= @localler.location %></p>
        </div>
      </div>

      <div class="local-bio">
        <h3>About me</h3>
        <p><%= @localler.description %></p>
      </div>

      <hr class ="line">

      <div>
        <h3>Activities I like</h3>
        <div>
          <ul>
            <% @localler.activities.each do |activity| %>
              <li><%= activity.title %></li>
            <% end %>
          </ul>
        </div>
        <div class='let-chat'>
          <% if @localler.user != current_user %>
            <% if Chat.where(localler: @localler, user: current_user).any? %>
              <%= link_to "Let's chat!", chat_path(Chat.find_by(localler: @localler, user: current_user)), class: "green-button-chat" %>
            <% else %>
              <%= link_to "Let's chat!", chats_path(localler: @localler), data: {turbo_method: :post}, class: "green-button-chat" %>
            <% end %>
            <% link_to "Back", :back, class: "green-outline-button-chat" %>
          <% end %>
        </div>
      </div>


      <div style="width: 100%; height: 300px;"
        data-controller="map-show"
        data-map-show-markers-value="<%= @markers.to_json %>"
        data-map-show-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
      <% # link_to "Back", :back, class: "text-light" %>
    </div>
  </div>
</div>

app/views/messages/_message.html.erb
<div class="message-send" id="message-<%= message.id %>">
  <small>
    <% #previous_message = @chat.messages[-2]%>
    <% #if previous_message.nil? || (message.created_at - previous_message.created_at) > 300 %>
      <i id="info-messager"><%= message.created_at.strftime("%b %e at %l:%M %p") %></i>
    <% #end %>
  </small>
  <p id="content-messager"><%= message.content %></p>
  <% previous_message = message %>
</div>

app/views/pages/home.html.erb
<div class="background">

  <div>
    <%= form_with url: locallers_path, class: "search-input", method: :get do %>
      <div class="auto-complete" data-controller="address-autocomplete" data-address-autocomplete-api-key-value="<%= ENV["MAPBOX_API_KEY"] %>">
        <%= text_field_tag :query,
          params[:query],
          class: "d-none",
          data: {address_autocomplete_target: "address"} %>
      </div>
      <%= button_tag(type: 'submit', class: "black-button") do %>
        <i>Confirm</i>
      <% end %>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<div class="navbar sticky-top navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <h3 class="m-0">Locally</h3>
    <% end %>

    <div>
      <div class="d-flex align-items-center justify-content-center">
        <% if user_signed_in? %>
          <% if Localler.where(user: current_user).any? %>
            <div class="d-flex flex-column align-items-center form-switch the-toggle me-2">
              <%= simple_form_for current_user.localler, data: {controller: "availability-toggle"} do |f| %>
                <%= f.input :availability, as: :boolean, label:"#{current_user.localler.availability? ? "online" : "offline"}", id: "toggle-button", label_html: {data: { availability_toggle_target: "label"}, class:"#{current_user.localler.availability? ? "form-check-label-available" : "form-check-label-unavailable"}"}, input_html: { data: {action: "click->availability-toggle#available click->availability-toggle#toggleLabel"}} %>
              <% end %>
            </div>
          <% elsif current_page?(new_localler_path) %>
          <% else %>
            <a href=""><%= link_to "Become a Localler", new_localler_path, class: "green-button-become2" %></a>
          <% end %>
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown">
            <%= cl_image_tag current_user.profile_picture.key, class: "avatar", alt: "dropdown menu" %>
          </a>

            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My Profile", dashboard_path, class: "dropdown-item" %>
              <%= link_to "My Messages", chats_path, class: "dropdown-item" %>
              <%= link_to "Log Out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>

          <% else %>
          <div class="nav-item">
            <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar2.html.erb
<div class="navbar sticky-top navbar-expand-sm navbar-light navbar-2">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <h3 class="m-0">Locally</h3>
    <% end %>

    <div>
      <div class="d-flex align-items-center justify-content-center">
        <% if user_signed_in? %>

          <% if Localler.where(user: current_user).any? %>
            <div class="d-flex flex-column align-items-center form-switch the-toggle me-2">
              <%= simple_form_for current_user.localler, data: {controller: "availability-toggle"} do |f| %>
                <%= f.input :availability, as: :boolean, label:"#{current_user.localler.availability? ? "online" : "offline"}", id: "toggle-button", label_html: {data: { availability_toggle_target: "label"}, class:"#{current_user.localler.availability? ? "form-check-label-available" : "form-check-label-unavailable"}"}, input_html: { data: {action: "click->availability-toggle#available click->availability-toggle#toggleLabel"}, class:"toggle"} %>
              <% end %>
            </div>
          <% elsif current_page?(new_localler_path) %>
          <% else %>
            <a href=""><%= link_to "Become a Localler", new_localler_path, class: "green-button-become" %></a>
          <% end %>

          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown">
            <%= cl_image_tag current_user.profile_picture.key, class: "avatar", alt: "dropdown menu" %>
          </a>

            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My Profile", dashboard_path, class: "dropdown-item" %>
              <%= link_to "My Messages", chats_path, class: "dropdown-item" %>
              <%= link_to "Log Out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>

          <% else %>
          <div class="nav-item">
            <%= link_to "Log In", new_user_session_path, class: "nav-link" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>